In [6]:
import numpy as np 
'''

a[start:stop]  # items start through stop-1
a[start:]      # items start through the rest of the array
a[:stop]       # items from the beginning through stop-1
a[:]           # a copy of the whole array

There is also the step value, which can be used with any of the above:

a[start:stop:step] # start through not past stop, by step

The key point to remember is that the :stop value represents the first value that is not in the selected slice. So, the difference between stop and start is the number of elements selected (if step is 1, the default).

The other feature is that start or stop may be a negative number, which means it counts from the end of the array instead of the beginning. So:

a[-1]    # last item in the array
a[-2:]   # last two items in the array
a[:-2]   # everything except the last two items

Similarly, step may be a negative number:

a[::-1]    # all items in the array, reversed
a[1::-1]   # the first two items, reversed
a[:-3:-1]  # the last two items, reversed
a[-3::-1]  # everything except the last two items, reversed

Python is kind to the programmer if there are fewer items than you ask for. For example, if you ask for a[:-2] and a only contains one element, you get an empty list instead of an error. Sometimes you would prefer the error, so you have to be aware that this may happen.
Relation to slice() object

The slicing operator [] is actually being used in the above code with a slice() object using the : notation (which is only valid within []), i.e.:

a[start:stop:step]

is equivalent to:

a[slice(start, stop, step)]

Slice objects also behave slightly differently depending on the number of arguments, similarly to range(), i.e. both slice(stop) and slice(start, stop[, step]) are supported. To skip specifying a given argument, one might use None, so that e.g. a[start:] is equivalent to a[slice(start, None)] or a[::-1] is equivalent to a[slice(None, None, -1)].

While the :-based notation is very helpful for simple slicing, the explicit use of slice() objects simplifies the programmatic generation of slicing.
'''

'\n\na[start:stop]  # items start through stop-1\na[start:]      # items start through the rest of the array\na[:stop]       # items from the beginning through stop-1\na[:]           # a copy of the whole array\n\nThere is also the step value, which can be used with any of the above:\n\na[start:stop:step] # start through not past stop, by step\n\nThe key point to remember is that the :stop value represents the first value that is not in the selected slice. So, the difference between stop and start is the number of elements selected (if step is 1, the default).\n\nThe other feature is that start or stop may be a negative number, which means it counts from the end of the array instead of the beginning. So:\n\na[-1]    # last item in the array\na[-2:]   # last two items in the array\na[:-2]   # everything except the last two items\n\nSimilarly, step may be a negative number:\n\na[::-1]    # all items in the array, reversed\na[1::-1]   # the first two items, reversed\na[:-3:-1]  # the last

In [7]:
print(np.__version__)

1.15.4


In [8]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/chirag/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Users/chirag/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/chirag/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C

In [9]:
null_vec = np.zeros(10); print(null_vec)  #creating null_vec of zeros

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
print("%d bytes" %(null_vec.size * null_vec.itemsize)) #finding memsize of array

80 bytes


In [11]:
#!python hello.py #calling python script from within notebook

In [12]:
Z = np.zeros(10) #create null_vec with one ele as 1
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
myrng = np.arange(10, 50, 2) #range with steps
print(myrng)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [14]:
myrev = myrng[::-1]; print(myrev) #reverse

[48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10]


In [15]:
mat3x3 = np.arange(9).reshape(3, 3)
print(mat3x3) #3 x 3 matrix

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
nz = np.nonzero([1, 0, 0, 1, 0, 1, 0, 1]) #nonzero ele within matrix
print(nz)

(array([0, 3, 5, 7], dtype=int64),)


In [17]:
nrand = np.random.random((3, 3)) #randm 3x3 matrix
print(nrand)

[[0.32593708 0.30560394 0.91356877]
 [0.20371129 0.99973092 0.43167669]
 [0.24035193 0.7710767  0.8269654 ]]


In [18]:
minmax = np.random.random((10, 10)) #find max and min from array
minm, maxm = minmax.min(), minmax.max()
print(minm, maxm)

0.019065272621829443 0.9850987044375432


In [19]:
mmean = np.random.random(30) #find mean
print(mmean.mean()) 

0.6067968158912388


In [20]:
border = np.ones((10, 10)) #creating array with one on border and zero inside
border[1:-1, 1:-1] = 0
print(border)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [21]:
border2 = np.ones((5, 5)) #padding of zeros around ones
print(np.pad(border2, pad_width=2, mode='constant', constant_values = 0))

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [22]:
mydiag = np.diag([1,2, 3, 4], k = 0) #printing on diagonals
print(mydiag)
mydiag = np.diag(4 + np.arange(4), k = -1) #printing diagonally just below the diagonals
print(mydiag)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0 0 0 0 0]
 [4 0 0 0 0]
 [0 5 0 0 0]
 [0 0 6 0 0]
 [0 0 0 7 0]]


In [23]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [24]:
value_below_diagonal = np.diag(1 + np.arange(4), k=-1) #K is the factor that decides below or above diagonal
print(value_below_diagonal)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [39]:
checkerboard_pattern = np.zeros((8, 8),dtype = int)
checkerboard_pattern[1::2,::2] = 1 
checkerboard_pattern[::2,1::2] = 1
print(checkerboard_pattern)


y = np.zeros((4,4), dtype = int)
y[1::2, ::2] = 1  # row-wise start from row 1, with 2 incremental steps
'''
y[1::2]
so we have 
0 0 0 0 
1 1 1 1 #row 1
0 0 0 0  
1 1 1 1 #row 1 + 2 (incremental) 
#visualise vertically
'''

'''
y[1::2, ::2]
0 0 0 0 
1 0 1 0 #row 1 -> start from column 0 and skip 2 i.e. set 1 for column 0 , then set 2 for column 0 + 2 , 0 + 4, and so on...
0 0 0 0  
1 0 1 0 #row 1 + 2 (incremental) 
#visualise horizontally
'''
print(y)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0 0 0 0]
 [1 0 1 0]
 [0 0 0 0]
 [1 0 1 0]]


In [40]:
print(np.unravel_index(99, (6,7,8))) #transfers indices in flatten array to non-flatten ones
#https://stackoverflow.com/questions/48135736/what-is-an-intuitive-explanation-of-np-unravel-index
'''
If you have a 2-D matrix, or array, you can reference it in different ways. You could type the (row, col), to get the value at (row, col), or you can give each cell a single-number index. unravel_index just translates between these two ways of referencing values in a matrix.
'''

'''
    >>> twobyfour = [
       [0,1,2,3], 
       [4,5,6,7]
    ]
     
    >>> np.unravel_index([0,7], (2,4))
    (array([0, 1]), array([0, 3]))
In plain English, when we run unravel_index in this example, we’re saying: “Get us the coordinates of the 0th and 7th elements of a 2-by-4 matrix.”
'''

(1, 5, 3)


In [41]:
zz = np.tile(np.array([[0,1], [1,0]]), (4,4))#tile(array, repititions)
print(zz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [43]:
random = np.random.random((5,5)) #normalise random matrix
random = (random - np.mean(random)) / (np.std(random))
print(random)

[[-1.96510388  0.57646027  0.61054593  0.07663482  1.0297177 ]
 [ 1.68236723  0.41620862  1.0791773  -0.6412934  -1.19191998]
 [ 1.90250139 -0.35009055  1.20427748  1.02148578 -0.06116254]
 [-0.21056638 -0.05133657 -0.74696164  0.83761097 -1.52565597]
 [-0.41861671 -0.41839984 -1.46040687 -0.56260115 -0.83287203]]


In [45]:
#create custom datatype describing color as 4 unsigned bytes
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])


In [51]:
#multiply 5x3 matrix by 3x2 matrix
z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [53]:
#given 1-d array negate all elements between 3 and 8, in place

negate = np.arange(11)
negate[(3 < negate) & (negate <= 8)] *= -1
print(negate)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [63]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [66]:
Z**Z
#2 << Z >> 2 --> illegal
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z --> illegal

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [68]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\chirag\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\chirag\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [70]:
#round off from float array
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-4.  5. -6.  2.  3. -5.  9. 10. -5. -2.]
