In [2]:
import numpy as np 
'''

a[start:stop]  # items start through stop-1
a[start:]      # items start through the rest of the array
a[:stop]       # items from the beginning through stop-1
a[:]           # a copy of the whole array

There is also the step value, which can be used with any of the above:

a[start:stop:step] # start through not past stop, by step

The key point to remember is that the :stop value represents the first value that is not in the selected slice. So, the difference between stop and start is the number of elements selected (if step is 1, the default).

The other feature is that start or stop may be a negative number, which means it counts from the end of the array instead of the beginning. So:

a[-1]    # last item in the array
a[-2:]   # last two items in the array
a[:-2]   # everything except the last two items

Similarly, step may be a negative number:

a[::-1]    # all items in the array, reversed
a[1::-1]   # the first two items, reversed
a[:-3:-1]  # the last two items, reversed
a[-3::-1]  # everything except the last two items, reversed

Python is kind to the programmer if there are fewer items than you ask for. For example, if you ask for a[:-2] and a only contains one element, you get an empty list instead of an error. Sometimes you would prefer the error, so you have to be aware that this may happen.
Relation to slice() object

The slicing operator [] is actually being used in the above code with a slice() object using the : notation (which is only valid within []), i.e.:

a[start:stop:step]

is equivalent to:

a[slice(start, stop, step)]

Slice objects also behave slightly differently depending on the number of arguments, similarly to range(), i.e. both slice(stop) and slice(start, stop[, step]) are supported. To skip specifying a given argument, one might use None, so that e.g. a[start:] is equivalent to a[slice(start, None)] or a[::-1] is equivalent to a[slice(None, None, -1)].

While the :-based notation is very helpful for simple slicing, the explicit use of slice() objects simplifies the programmatic generation of slicing.
'''

'\n\na[start:stop]  # items start through stop-1\na[start:]      # items start through the rest of the array\na[:stop]       # items from the beginning through stop-1\na[:]           # a copy of the whole array\n\nThere is also the step value, which can be used with any of the above:\n\na[start:stop:step] # start through not past stop, by step\n\nThe key point to remember is that the :stop value represents the first value that is not in the selected slice. So, the difference between stop and start is the number of elements selected (if step is 1, the default).\n\nThe other feature is that start or stop may be a negative number, which means it counts from the end of the array instead of the beginning. So:\n\na[-1]    # last item in the array\na[-2:]   # last two items in the array\na[:-2]   # everything except the last two items\n\nSimilarly, step may be a negative number:\n\na[::-1]    # all items in the array, reversed\na[1::-1]   # the first two items, reversed\na[:-3:-1]  # the last

In [3]:
print(np.__version__)

1.15.4


In [4]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/chirag/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Users/chirag/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/chirag/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C

In [5]:
null_vec = np.zeros(10); print(null_vec)  #creating null_vec of zeros

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
print("%d bytes" %(null_vec.size * null_vec.itemsize)) #finding memsize of array

80 bytes


In [7]:
#!python hello.py #calling python script from within notebook

In [8]:
Z = np.zeros(10) #create null_vec with one ele as 1
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
myrng = np.arange(10, 50, 2) #range with steps
print(myrng)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [10]:
myrev = myrng[::-1]; print(myrev) #reverse

[48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10]


In [11]:
mat3x3 = np.arange(9).reshape(3, 3)
print(mat3x3) #3 x 3 matrix

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
nz = np.nonzero([1, 0, 0, 1, 0, 1, 0, 1]) #nonzero ele within matrix
print(nz)

(array([0, 3, 5, 7], dtype=int64),)


In [13]:
nrand = np.random.random((3, 3)) #randm 3x3 matrix
print(nrand)

[[0.10384201 0.37902159 0.90077772]
 [0.85215856 0.46737916 0.63500506]
 [0.57237124 0.53770297 0.23621842]]


In [14]:
minmax = np.random.random((10, 10)) #find max and min from array
minm, maxm = minmax.min(), minmax.max()
print(minm, maxm)

0.005017580679529066 0.9754329803849029


In [15]:
mmean = np.random.random(30) #find mean
print(mmean.mean()) 

0.4244000177960579


In [16]:
border = np.ones((10, 10)) #creating array with one on border and zero inside
border[1:-1, 1:-1] = 0
print(border)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [17]:
border2 = np.ones((5, 5)) #padding of zeros around ones
print(np.pad(border2, pad_width=1, mode='constant', constant_values = 0))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [18]:
mydiag = np.diag([1,2, 3, 4], k = 0) #printing on diagonals
print(mydiag)
mydiag = np.diag(4 + np.arange(4), k = -1) #printing diagonally just below the diagonals
print(mydiag)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0 0 0 0 0]
 [4 0 0 0 0]
 [0 5 0 0 0]
 [0 0 6 0 0]
 [0 0 0 7 0]]


In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [20]:
value_below_diagonal = np.diag(1 + np.arange(4), k=-1) #K is the factor that decides below or above diagonal
print(value_below_diagonal)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [21]:
checkerboard_pattern = np.zeros((8, 8),dtype = int)
checkerboard_pattern[1::2,::2] = 1 
checkerboard_pattern[::2,1::2] = 1
print(checkerboard_pattern)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
print(np.unravel_index(99, (6,7,8))) #need to understand this more


(1, 5, 3)


In [26]:
zz = np.tile(np.array([[0,1], [1,0]]), (4,4))#tile(array, repititions)
print(zz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [31]:
random = np.random.random((5,5)) #normalise random matrix
random = (random - np.mean(2)) / (np.std(random))
print(random)

[[-6.96662954 -7.47011999 -5.76617423 -6.13768656 -4.52658115]
 [-5.51550405 -7.85203337 -6.93300095 -7.21920325 -5.13716362]
 [-4.85158295 -5.04326754 -4.4759258  -7.14861819 -6.55496536]
 [-6.62721795 -5.0041197  -5.6983315  -4.77443565 -6.03200687]
 [-4.73250274 -7.21462473 -5.93503448 -6.44004895 -6.68737055]]
