In [1]:
import numpy as np 
np.__version__

'1.15.4'

In [2]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
type(l[0])

int

In [4]:
l2 = [str(x) for x in l]
l2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [5]:
type(l2[3])

str

In [6]:
l3 = [True, '1', 2, 3 ,4]
l3
[type(i) for i in l3]

[bool, str, int, int, int]

In [7]:
#numpy array contain single pointer to one contigous block of data
#python list contains pointer to block of pointer which in turn point to full Python object like Python integer
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [8]:
np.array([3.14, 5, 6, 5.9])

array([3.14, 5.  , 6.  , 5.9 ])

In [9]:
np.array([1,2,3,4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [10]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [11]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.full((4,4), 3.14) #full(shape, value)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [13]:
np.arange(0, 25, 2) #arange(x, y+1, strides)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [14]:
np.linspace(0, 1, 5) #create array of 5 values evenly spaced between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
np.random.random((3,3)) #uniformly ditributed 3 x 3 array having random values between 0 and 1

array([[0.88969457, 0.02151332, 0.30456833],
       [0.03803956, 0.80082017, 0.10459325],
       [0.17195346, 0.38926018, 0.93628112]])

In [16]:
np.random.normal(0, 1,(3,3)) #3 x 3 array having random values between 0 and 1 with mean 0 and sd 1

array([[-1.75788851, -0.47462392,  0.6234287 ],
       [ 0.57880743, -0.52390328, -0.27916705],
       [ 0.17508473,  1.23691819,  0.2574343 ]])

In [17]:
np.random.randint(0, 10, (3,3)) #3 x 3 random ints in interval [0, 10)

array([[7, 2, 9],
       [8, 3, 7],
       [3, 1, 2]])

In [18]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.empty(3) # uninitialised array of 3 ints

array([1., 1., 1.])

In [20]:
'''bool_ 
int_ #int64
intc
intp
int8
int16
int32
int64
uint8
uint16
uint32
unint64
float_
float_t16
float32
float64
complex_
complex64
complex128
'''

'bool_ \nint_ #int64\nintc\nintp\nint8\nint16\nint32\nint64\nuint8\nuint16\nuint32\nunint64\nfloat_\nfloat_t16\nfloat32\nfloat64\ncomplex_\ncomplex64\ncomplex128\n'

In [21]:
#np array attrs
np.random.seed(0) #seed for regerating same random arrs

x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (4,3))
x3 = np.random.randint(10, size = (3,4,5))

print(x1, x2, x3)

[5 0 3 3 7 9] [[3 5 2]
 [4 7 6]
 [8 8 1]
 [6 7 7]] [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [22]:
print(x1.shape) #shape - size of each dimension
print(x2.ndim) #dimension 
print(x3.size) #total size of array

(6,)
2
60


In [23]:
x3.dtype

dtype('int32')

In [24]:
#size in bytes -> itemsize || total size in bytes of array -> nbytes
#nbytes = itemsize * size
print(x3.itemsize)
print(x3.nbytes)

4
240


In [25]:
x1[-1]
x1[-2]

7

In [26]:
x3[0,3] #numpy arrays are fixed type

array([1, 3, 3, 3, 7])

In [27]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x[:5]

array([0, 1, 2, 3, 4])

In [29]:
x[4:7]

array([4, 5, 6])

In [30]:
x[5:]

array([5, 6, 7, 8, 9])

In [31]:
x[::2]

array([0, 2, 4, 6, 8])

In [32]:
x[1::2]

array([1, 3, 5, 7, 9])

In [33]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [34]:
x[5::-2]

array([5, 3, 1])

In [35]:
x2[::-1, ::-1]

array([[7, 7, 6],
       [1, 8, 8],
       [6, 7, 4],
       [2, 5, 3]])

In [36]:
x2[:,0] #accessing column of x2

array([3, 4, 8, 6])

In [37]:
x2[0, :] #first row of x2

array([3, 5, 2])

In [38]:
#by default numpy arrays work as deep copy
x2_sub = x2[:2, :2]
x2_sub
x2_sub[1,1] = 100
print(x2) #here 100 is updated

[[  3   5   2]
 [  4 100   6]
 [  8   8   1]
 [  6   7   7]]


In [39]:
#so for shallow copy, we use .copy()

x2_sub_copy = x2[:2, :2].copy()

print(x2_sub_copy)

[[  3   5]
 [  4 100]]


In [40]:
grid= np.arange(1, 10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
x = np.array([1,2,3])
print(x)

[1 2 3]


In [42]:
x.reshape((1,3))

array([[1, 2, 3]])

In [43]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [44]:
x = np.array([1,2])
y = np.array([3,4])
np.concatenate([x, y])

array([1, 2, 3, 4])

In [45]:
z = [100, 100, 100]
np.concatenate([x, y, z])

array([  1,   2,   3,   4, 100, 100, 100])

In [46]:
grid = np.array([range(i, i + 3) for i in range(1, 4)])
print(grid)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [47]:
np.concatenate([grid, grid]) #concatenate along first axis
np.concatenate([grid, grid], axis = 1) #concatenate along second axis


array([[1, 2, 3, 1, 2, 3],
       [2, 3, 4, 2, 3, 4],
       [3, 4, 5, 3, 4, 5]])

In [48]:
x = np.array([1, 2, 3])
grid = np.array([[4, 5, 6], [6, 7, 8]])

In [49]:
np.vstack([x, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [50]:
y = np.array([[2], [3]])
np.hstack([y, grid])

array([[2, 4, 5, 6],
       [3, 6, 7, 8]])

In [51]:
x = np.array([1, 2, 3, 5, 6, 7, 8])
x1, x2, x3 = np.split(x , [3,5])
print(x1, x2, x3)

[1 2 3] [5 6] [7 8]


In [52]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
up, low = np.vsplit(grid, [2])
print(up, low)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


In [54]:
l, r = np.hsplit(grid, [2])
print(l)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [55]:
np.random.seed(0)
def compute_reciprocals(val):
    op = np.empty(len(val))
    for i in range(len(val)):
        op[i] = 1.0 / val[i]
    return op

compute_reciprocals(np.random.randint(1, 10, size = 5))

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [56]:
big_ar = np.random.randint(1, 100, size = 100000)
big_ar

array([10, 84, 22, ..., 85, 15, 53])

In [57]:
'''
Vectorized operations in NumPy are implemented via ufuncs, whose main purpose is
to quickly execute repeated operations on values in NumPy arrays. Ufuncs are
extremely flexible—before we saw an operation between a scalar and an array, but we
can also operate between two arrays
'''

np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [58]:
#ufuncs

x = np.arange(4)
print(x)
print(x + 5)
print(x - 5)
print(x * 5)
print(x /2) 
print(x // 2)
print(x ** 2)
print(x % 2)
print(-x)

[0 1 2 3]
[5 6 7 8]
[-5 -4 -3 -2]
[ 0  5 10 15]
[0.  0.5 1.  1.5]
[0 0 1 1]
[0 1 4 9]
[0 1 0 1]
[ 0 -1 -2 -3]


In [59]:
np.add(x, 2)

array([2, 3, 4, 5])

In [60]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)
np.absolute(x)

array([2, 1, 0, 1, 2])

In [61]:
x = [-1, 0 , 1]
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))
#similarly sin, cos, tan

[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


In [62]:
x = [1, 2, 3]
print(np.exp(x))
print(np.exp2(x))
print(np.power(3, x))
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]
[ 3  9 27]
[0.         0.69314718 1.09861229]
[0.        1.        1.5849625]
[0.         0.30103    0.47712125]


In [63]:
#scpiy.special
from scipy import special
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x) =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2) =", special.beta(x, 2))

gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2) = [0.5        0.03333333 0.00909091]


In [64]:
x = np.arange(5)
y = np.empty(5)

np.multiply(x, 10, out=y)
print(y)


y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 0. 10. 20. 30. 40.]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [65]:
x = np.arange(1, 6)
np.add.reduce(x) #sum of all eles


15

In [66]:
np.multiply.reduce(x)

120

In [67]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [68]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [69]:
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [70]:
np.sum(np.random.random(100))

47.2672505298031

In [71]:
np.min(np.random.random(100)), np.max(np.random.random(100))

(0.01104066372983159, 0.989703528986501)

In [72]:
'''
Numpy agg func:
sum
prod
mean
std
var
min
max
argmin
argmax
median
percentile
any
all
#NAN safe versions also exist
'''

'\nNumpy agg func:\nsum\nprod\nmean\nstd\nvar\nmin\nmax\nargmin\nargmax\nmedian\npercentile\nany\nall\n#NAN safe versions also exist\n'

In [73]:
 !head -5 data/jvp/president_heights.csv

order,name,height(cm)
1,George Washington,189
2,John Adams,170
3,Thomas Jefferson,189
4,James Madison,163


In [74]:
import pandas as pd
data = pd.read_csv('data/jvp/president_heights.csv')
height = np.array(data['height(cm)'])
print(height)

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]


In [75]:
print(height.mean())
print(height.std())
print(height.min())
print(height.max())

179.73809523809524
6.931843442745892
163
193


In [76]:
print(np.percentile(height, 25))
print(np.percentile(height, 75))

174.25
183.0


In [77]:
import matplotlib.pyplot as plt
import seaborn
seaborn.set()
plt.hist(height)
plt.title("heights")
plt.xlabel("height cm")
plt.ylabel("number")

Text(0, 0.5, 'number')

In [78]:
M = np.ones((3, 3))
M + 5 #broadcasting 5 to all the values in the matrix

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [79]:
#broadcasting in depth--
#broadcasting means applying binary functions (add, sub, mul etc..) on array of diff sizes

a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
a + b

array([3, 5, 7])

In [80]:
M = np.ones((3, 3))
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])